---
title: "Untitled"
output: html_document
date: "2024-08-27"
---


```{r}
#simulate data from various negative binomial distributions
B <- 50000
plist <- c(.1,.5,.9)
mu <- 50
numDatasets <- 5
mat <- matrix(0, nrow=B+2,ncol=length(plist)*numDatasets)
count <- 1
n <- 1000
for(i in 1:length(plist)){
  for(j in 1:numDatasets){
    set.seed(j)
    p <- plist[i]
    r <- mu*p/(1-p)
    print(r)
    x <- rnbinom(B, r,p)
    
    #print(var(x)/mean(x))
    mat[,count] <- c(p, j, x)
    count <- count + 1
  }
}

write.csv(mat, "NBdata.csv")
#hist(x)
```

```{r}
dgamma_count <- function(k,alpha,beta){
  return(ifelse(k == 0,1-pgamma(1,alpha*(k+1),beta),pgamma(1,alpha*k, beta) - pgamma(1,alpha*(k+1), beta)))
}
```


```{r}
plist <- c(.1,.5,.9)
begin = 0
end = 100
mu <- 50
count <- 1
mat <- matrix(0,nrow=length(plist),ncol=length(begin:end))
for(p in plist){
  r <- mu*p/(1-p)
  x <- dnbinom(begin:end,r,p)
  mat[count,] <- x
  count <- count + 1
}
write.csv(mat, "NBpmf.csv")
```





```{r}
lower_gamma_inc <- function(a,b){
  return(1-gammainc(a,b)/gamma(a))
}

betanew <- beta*Th
total = 0
xlist <- seq(0,1000,1)
problist <- rep(0,length(xlist))
total = 0 
for(i in 1:length(xlist)){
  n <- xlist[i]
  if(n == 0){
    #temp = 1-lower_gamma_inc(alpha*(n+1),betanew)
    temp = 1-pgamma(1,alpha*(n+1),betanew)
  }else{
    #temp = lower_gamma_inc(alpha*n, betanew) - lower_gamma_inc(alpha*(n+1), betanew)
    temp = pgamma(1,alpha*n, betanew) - pgamma(1,alpha*(n+1), betanew)
  }
  if(!is.na(temp)){
      problist[i] <- temp
    }else{
      problist[i] <- 0
    }
  total = total + temp
}

midpoints <- barplot(table(samp_B)/B,col=rgb(0, 0, 1, 0.5),ylim=c(0,max(problist)+.01))
points(midpoints,problist[as.numeric(names(table(samp_B))) + 1],pch=20)
```

```{r}
dgamma_count(0:50,1.2,25)
```


```{r}
varmaxnormal <- function(D,B){
  result <- rep(0,B)
  for(b in 1:B){
    result[b] <- max(rnorm(D))
  }
  return(var(result))
}
varmaxnormal(15,100000)
```



