---
title: "fanofactorlimits"
output: html_document
date: "2024-05-25"
---

```{r}
muvec <- seq(1,100,by=1)
#fano factor plot
dvec <- c(1,2,3,4,5,10,20,50,100)

B <- 100000
mean_mat <- matrix(0,nrow = length(muvec),ncol=length(dvec))
variances_mat <- matrix(0,nrow = length(muvec),ncol=length(dvec))

for(i in 1:length(muvec)){
  mu <- muvec[i]
  for(j in 1:length(dvec)){
    d <- dvec[j]
    Z_B <- c()
    Y_B <- c()
    for(k in 1:B){
      m_D <- rpois(d, mu)
      Z <- max(m_D)
      Z_B <- c(Z_B, Z)
    }
    mean_mat[i,j] <- mean(Z_B)
    variances_mat[i,j] <- var(Z_B)
  }
}

library(tidyverse)
fano_mat <- variances_mat/mean_mat
df <- data.frame(fano_mat)
colnames(df) <- as.character(dvec)
df <- df %>% pivot_longer(cols = colnames(df), names_to = "D")
df$D <- factor(df$D, levels = as.character(dvec))#,"5", "10","20","50","100","1000"

muvec_other <- c()
for(mu in muvec){
  muvec_other <- c(muvec_other, rep(mu,length(dvec)))
}
save(df,file="/Users/jimmylederman/Desktop/PoissonMax/theoryworkbooks/fano1.Rda")
```

```{r}
#load data
load(file="/Users/jimmy/Desktop/OrderStats/figures/section2/fano1.Rda")
load(file="/Users/jimmy/Desktop/OrderStats/figures/section2/fano2.Rda")
#combine df

muvec <- seq(1,100,by=1)
muvec_other <- c()
dvec <- c(1,2,3,4,5,10,20,50,100)
for(mu in muvec){
  muvec_other <- c(muvec_other, rep(mu,length(dvec)))
}
df$mu <- muvec_other

muvec <- seq(.01,2,by=.02)
muvec_other <- c()
for(mu in muvec){
  muvec_other <- c(muvec_other, rep(mu,length(dvec)))
}
df2$mu <- muvec_other
df2$plot <- 1
df$plot <- 2
df_all <- rbind(df[which(df$mu >=2),],df2)

```

```{r}


library(tidyverse)
ggplot() + 
  geom_point(data = df_all, aes(x = df_all$mu, y = value, color = D)) +
  labs(y = "Fano Factor", x = expression(mu)) +
  facet_grid(~plot,scales="free_x") +
  geom_hline(yintercept = (pi-1)/pi,
             linetype = "dashed", color = "black") + theme_bw() + theme(strip.text = element_blank()) 
#ggsave("fanoplot.png", plot = p, width = 10, height = 6, units = "in")
```

```{r}
muvec <- seq(.01,2,by=.02)
muvec_other <- c()
for(mu in muvec){
  muvec_other <- c(muvec_other, rep(mu,length(dvec)))
}
library(tidyverse)
ggplot() + 
  geom_point(data = df2, aes(x = muvec_other, y = value, color = D)) +
  labs(y = "Fano Factor", x = expression(mu)) +
  geom_hline(yintercept = (pi-1)/pi,
             linetype = "dashed", color = "black") + theme_bw()
```


```{r}
#fano factor plot
muvec <- seq(.01,2,by=.02)
dvec <- c(1,2,3,4,5,10,20,50,100)

B <- 100000
mean_mat <- matrix(0,nrow = length(muvec),ncol=length(dvec))
variances_mat <- matrix(0,nrow = length(muvec),ncol=length(dvec))

for(i in 1:length(muvec)){
  mu <- muvec[i]
  for(j in 1:length(dvec)){
    d <- dvec[j]
    Z_B <- c()
    Y_B <- c()
    for(k in 1:B){
      m_D <- rpois(d, mu)
      Z <- max(m_D)
      Z_B <- c(Z_B, Z)
    }
    mean_mat[i,j] <- mean(Z_B)
    variances_mat[i,j] <- var(Z_B)
  }
}

library(tidyverse)
fano_mat <- variances_mat/mean_mat
df2 <- data.frame(fano_mat)
colnames(df2) <- as.character(dvec)
df2 <- df2 %>% pivot_longer(cols = colnames(df2), names_to = "D")
df2$D <- factor(df2$D, levels = as.character(dvec))#,"5", "10","20","50","100","1000"

muvec_other <- c()
for(mu in muvec){
  muvec_other <- c(muvec_other, rep(mu,length(dvec)))
}
save(df2,file="/Users/jimmylederman/Desktop/PoissonMax/theoryworkbooks/fano2.Rda")
```


```{r}
library(tidyverse)
ggplot() + 
  geom_point(data = df2, aes(x = muvec_other, y = value, color = D)) +
  labs(y = "Fano Factor", x = "mu") +
  geom_hline(yintercept = (pi-1)/pi,
             linetype = "dashed", color = "red") #+
  # geom_hline(yintercept = var(rmaxnorm(100000,5,mean=0,sd=1)),
  #            linetype = "dashed", color = "red") +
  # geom_hline(yintercept = var(rmaxnorm(100000,10,mean=0,sd=1)),
  #            linetype = "dashed", color = "red") +
  # geom_hline(yintercept = var(rmaxnorm(100000,20,mean=0,sd=1)),
  #            linetype = "dashed", color = "red") +
  # geom_hline(yintercept = var(rmaxnorm(100000,50,mean=0,sd=1)),
  #            linetype = "dashed", color = "red") +
  # geom_hline(yintercept = var(rmaxnorm(100000,100,mean=0,sd=1)),
  #            linetype = "dashed", color = "red")
```


```{r}
#fano factor plot
muvec <- seq(1,50,by=1)
dvec <- c(2,5,10,20,50,100)

B <- 10000
mean_mat <- matrix(0,nrow = length(muvec),ncol=length(dvec))
variances_mat <- matrix(0,nrow = length(muvec),ncol=length(dvec))

for(i in 1:length(muvec)){
  mu <- muvec[i]
  for(j in 1:length(dvec)){
    d <- dvec[j]
    Z_B <- c()
    Y_B <- c()
    for(k in 1:B){
      m_D <- rpois(d, mu)
      m_D <- sort(m_D, decreasing = TRUE)
      Z <- m_D[2]
      Z_B <- c(Z_B, Z)
    }
    mean_mat[i,j] <- mean(Z_B)
    variances_mat[i,j] <- var(Z_B)
  }
}

library(tidyverse)
fano_mat <- variances_mat/mean_mat
df <- data.frame(fano_mat)
colnames(df) <- as.character(dvec)
df <- df %>% pivot_longer(cols = colnames(df), names_to = "D")
df$D <- factor(df$D, levels = as.character(dvec))#,"5", "10","20","50","100","1000"

muvec_other <- c()
for(mu in muvec){
  muvec_other <- c(muvec_other, rep(mu,length(dvec)))
}

```

```{r}
library(tidyverse)
ggplot() + 
  geom_point(data = df, aes(x = muvec_other, y = value, color = D)) +
  labs(y = "Fano Factor", x = "mu") +
  geom_hline(yintercept = (pi-1)/pi,
             linetype = "dashed", color = "red") #+
  # geom_hline(yintercept = var(rmaxnorm(100000,5,mean=0,sd=1)),
  #            linetype = "dashed", color = "red") +
  # geom_hline(yintercept = var(rmaxnorm(100000,10,mean=0,sd=1)),
  #            linetype = "dashed", color = "red") +
  # geom_hline(yintercept = var(rmaxnorm(100000,20,mean=0,sd=1)),
  #            linetype = "dashed", color = "red") +
  # geom_hline(yintercept = var(rmaxnorm(100000,50,mean=0,sd=1)),
  #            linetype = "dashed", color = "red") +
  # geom_hline(yintercept = var(rmaxnorm(100000,100,mean=0,sd=1)),
  #            linetype = "dashed", color = "red")
```


```{r}
rmaxnorm <- function(N,D,mean,sd){
  x <- c()
  for(i in 1:N){
    x <- c(x, max(rnorm(n=D,mean=mean,sd=sd)))
  }
 return(x)
}
```


```{r}
mu <- 100
x <- rmaxnorm(100000,10,mean=0,sd=1)
mean <- mu + sqrt(mu)*mean(x) + 1/6*(mean(x^2)-1)
var <- mu*var(x) + 1/3*sqrt(mu)*cov(x,x^2)
var/mean
```

```{r}
(pi-1)/pi
var(x)
```

```{r}
rmaxpois <- function(N,D,mu){
  x <- c()
  for(i in 1:N){
    x <- c(x, max(rpois(n=D,lambda=mu)))
  }
 return(x)
}
```

```{r}
mu = .01
x = rmaxpois(100000,1,mu)
var(x)
x = rmaxpois(100000,2,mu)
var(x)
x = rmaxpois(100000,3,mu)
var(x)
x = rmaxpois(100000,4,mu)
var(x)
x = rmaxpois(100000,5,mu)
var(x)
```
```{r}
mu <- 0.01
mu + mu*(besselI(2*mu, 0, expon.scaled = TRUE)
          + besselI(2*mu, 1, expon.scaled = TRUE))
```



