---
title: "Dregression"
output: html_document
date: "2025-04-30"
---

```{r}
Dmean <- as.matrix(read.csv("/Users/jimmy/Desktop/OrderStats/figures/birds/Dregression/D_NMmean.csv"))
X <- as.matrix(read.csv("/Users/jimmy/Desktop/OrderStats/data/birds/birds_dunsonX.csv"))
```

```{r}
Xdf <- read.csv("/Users/jimmy/Desktop/OrderStats/data/birds/birds_dunsonX.csv")
```


```{r}
index <- sample(1:nrow(X), 100)
Xsub <- X[index,]
Dmeansub <- Dmean[index,]
```


```{r}
values <- c(Dmean)
species <- rep(1:ncol(Dmean), nrow(Dmean))

repeated_mat <- X[rep(1:nrow(X), each = ncol(Dmean)), ]
Dmeanvec <- cbind(values, species,repeated_mat)
```


```{r}
df <- data.frame(Dmeanvec)
df$X<- NULL
df$X.Intercept. <- NULL
df[] <- lapply(df, function(x) as.numeric(as.character(x)))
df$species <- as.factor(species)
```

```{r}
# plot(df$VMI_PC1, df$values, pch = ".", ylab="Posterior mean of D")
hist(df$values[which(df$species != 66)])
# mean(df$values[which(df$VMI_PC1 != 6)])
```


```{r}
model1 <- lm(data=df,values~.)
```

```{r}
summary(model1)
```

```{r}
plot(model2$fitted.values, model1$residuals)
```



```{r}
model2 <- lm(data=df,values~Mixed_Forest+Shrubs+Grasslands_Wetlands+Barren+Urban+Water_Bodies+Coastal+species)
summary(model2)
```




