---
title: "fanofactormedians"
output: html_document
date: "2024-11-16"
---

```{r}
muvec <- seq(1,100,by=1)
#fano factor plot
dvec <- c(1,3,5,7,9,11,21,51,101)

B <- 10000
mean_mat <- matrix(0,nrow = length(muvec),ncol=length(dvec))
variances_mat <- matrix(0,nrow = length(muvec),ncol=length(dvec))

for(i in 1:length(muvec)){
  mu <- muvec[i]
  for(j in 1:length(dvec)){
    d <- dvec[j]
    Z_B <- c()
    Y_B <- c()
    for(k in 1:B){
      m_D <- rpois(d, mu)
      Z <- median(m_D)
      Z_B <- c(Z_B, Z)
    }
    mean_mat[i,j] <- mean(Z_B)
    variances_mat[i,j] <- var(Z_B)
  }
}

library(tidyverse)
fano_mat <- variances_mat/mean_mat
df <- data.frame(fano_mat)
colnames(df) <- as.character(dvec)
df <- df %>% pivot_longer(cols = colnames(df), names_to = "D")
df$D <- factor(df$D, levels = as.character(dvec))#,"5", "10","20","50","100","1000"

muvec_other <- c()
for(mu in muvec){
  muvec_other <- c(muvec_other, rep(mu,length(dvec)))
}
```

```{r}
#fano factor plot
muvec <- seq(.01,2,by=.02)
dvec <- c(1,3,5,7,9,11,21,51,101)

B <- 10000
mean_mat <- matrix(0,nrow = length(muvec),ncol=length(dvec))
variances_mat <- matrix(0,nrow = length(muvec),ncol=length(dvec))

for(i in 1:length(muvec)){
  mu <- muvec[i]
  for(j in 1:length(dvec)){
    d <- dvec[j]
    Z_B <- c()
    Y_B <- c()
    for(k in 1:B){
      m_D <- rpois(d, mu)
      Z <- median(m_D)
      Z_B <- c(Z_B, Z)
    }
    mean_mat[i,j] <- mean(Z_B)
    variances_mat[i,j] <- var(Z_B)
  }
}

library(tidyverse)
fano_mat <- variances_mat/mean_mat
df2 <- data.frame(fano_mat)
colnames(df2) <- as.character(dvec)
df2 <- df2 %>% pivot_longer(cols = colnames(df2), names_to = "D")
df2$D <- factor(df2$D, levels = as.character(dvec))#,"5", "10","20","50","100","1000"

muvec_other <- c()
for(mu in muvec){
  muvec_other <- c(muvec_other, rep(mu,length(dvec)))
}
```

```{r}
muvec <- seq(1,100,by=1)
muvec_other <- c()
for(mu in muvec){
  muvec_other <- c(muvec_other, rep(mu,length(dvec)))
}
df$mu <- muvec_other

muvec <- seq(.01,2,by=.02)
muvec_other <- c()
for(mu in muvec){
  muvec_other <- c(muvec_other, rep(mu,length(dvec)))
}
df2$mu <- muvec_other
df2$plot <- 1
df$plot <- 2
df_all <- rbind(df[which(df$mu >=2),],df2)
```

```{r}
library(tidyverse)
ggplot() + 
  geom_point(data = df_all, aes(x = df_all$mu, y = value, color = D)) +
  labs(y = "Fano Factor", x = expression(mu)) +
  facet_grid(~plot,scales="free_x")  + theme_bw() + theme(strip.text = element_blank()) 
#ggsave("fanoplot.png", plot = p, width = 10, height = 6, units = "in")
```



