---
title: "distributionD"
output: html_document
date: "2024-07-18"
---

```{r}

```

```{r}
p <- .3
x <- 20
mu <- 30
#for one data point
maxlik <- function(d,x,mu){
  return(ppois(x,mu)^d - ppois(x-1,mu)^d)
}
probD <- function(d,p,X,mu){
  denom1 <- 1/(1- ((1-p)*ppois(x,mu)))
  print(denom1)
  denom2 <- 1/(1- ((1-p)*ppois(x-1,mu)))
  print(denom2)
  num <- (1-p)^d * maxlik(d,x,mu)
  print(num)
  return(num/(denom1-denom2))
}
results <- sapply(1:10, function(d) probD(d, p, x, mu))
data <- data.frame(
  categories = as.factor(1:10),
  values = results)
ggplot(data, aes(x = categories, y = values)) +
  geom_bar(stat = "identity") +
  labs(title = "Distribution over D", x = "D", y = "probability") +
  theme_minimal()
```



```{r}
probD <- function(d,p,X,mu){
  denom1 <- 1/(1- ((1-p)*ppois(x,mu)))
  denom2 <- 1/(1- ((1-p)*ppois(x-1,mu)))
  totallik <- 1
  for(x in X){
    totallik <- totallik*maxlik(d,x,mu)
  }
  num <- (1-p)^d * totallik
  return(num/(denom1-denom2))
}
```

```{r}
D <- 2:5
B <- 100000
for(d in D){
  beep <- rep(0,B)
  for(i in 1:B){
    beep[i] <- max(rnorm(d))
  }
  print(var(beep))
}

```


```{r}
y1 <-c(0.020846309626054167, 0.01946605203352451, 0.017415289866209594, 0.01546644049387253, 0.014163330289325756)
x1 <- c(1,(pi-1)/pi, 0.5602373, 0.4896867, 0.4459626)
y2 <- c(0.02079938700695805, 0.020675526058781788, 0.020467889896189664, 0.020116807095726753, 0.019764287759910217, 0.019625037489745235)
x2 <- ((pi-1)/pi)/seq(.7, .95, .05)

plot(x1,y1, col="blue", pch=20, xlab="Dispersion Index", ylab="Heldout 'Info Rate'",
     main="Nba Scores: Heldout 'Info Rate' for various Max models")
points(x2,y2, col="red", pch=20)
legend("bottomright", 
       legend = c("Poisson D=1-5", "Negative Binomial D=2, p=.7-.95"), 
       col = c("blue", "red"), 
       pch = 20)
```



