---
title: "Untitled"
output: html_document
date: "2024-10-11"
---

```{r}
rmaxPois <- function(n, mu, D){
  result <- rep(0,n)
  for(i in 1:n){
    sample <- rpois(D, mu)
    result[i] <- max(sample)
  }
  return(result)
}
```







```{r}
g <- function(x){
 return (x/(1+(besselI(2*x, 0, expon.scaled = TRUE)
          + besselI(2*x, 1, expon.scaled = TRUE))))
}
```

```{r}
Y <- seq(1,100,1)
plot(Y,g(Y),pch=20)
abline(a=0,b=1)
```



```{r}
bessel_adjust <- function(mu){
  return (1/(1+(besselI(2*mu, 0, expon.scaled = TRUE)
          + besselI(2*mu, 1, expon.scaled = TRUE))))
}
#draw a MaxPoisson
D <- 3
mu <- 100
Ylast <- rmaxPois(1, mu, D)
B <- 1000
b <- bessel_adjust(mu)
errorvec <- rep(0,B)
for(i in 1:B){
  Y <- rmaxPois(1000,Ylast*b - D,D)
  errorvec[i] <- mean(Y) - Ylast
}



```
```{r}
hist(errorvec)
```




```{r}
mu <- 1
alpha <- 1/(1+(besselI(2*mu, 0, expon.scaled = TRUE)
          + besselI(2*mu, 1, expon.scaled = TRUE)))
mean(rmaxPois(1000, mu, 2))*alpha
```

```{r}

```



```{r}
rmaxNegBin <- function(n, r, p, D){
  result <- rep(0,n)
  for(i in 1:n){
    sample <- rnbinom(D, r, p)
    result[i] <- max(sample)
  }
  return(result)
}
r <- 100
p <- (pi - 1) / pi
n <- 1000000
x <- rmaxNegBin(n, r, p, 2)
var(x)/mean(x)
y <- rpois(n, mean(x))
var(y)/mean(y)
```

```{r}
mean(x)
```


```{r}
hist(x,  col = rgb(0.9, 0.8, 0.6, 0.5))
hist(y, add=TRUE, col = rgb(0.2, 0.2, 0.6, 0.5))
```


```{r}
rmaxPois <- function(n, mu, D){
  result <- rep(0,n)
  for(i in 1:n){
    sample <- rpois(D, mu)
    result[i] <- max(sample)
  }
  return(result)
}
B <- 100000
mu <- 1000
sum(rmaxPois(B,mu,2) > mu)/B
```

