---
title: "Untitled"
output: html_document
date: "2023-11-02"
---

```{r}
#simulation for 2 Poissons
D <- 2
mu <- 2.6
Y_B <- c()
Z_B <- c()
B <- 10000
for(i in 1:B){
  m_D <- rpois(D, mu)
  Y <- min(m_D) 
  Z <- max(m_D)
  Y_B <- c(Y_B, Y)
  Z_B <- c(Z_B, Z)
}
#mean(Y_B)
#mean(Z_B)

#hist(Z_B)
E_max <- mu + mu*(besselI(2*mu, 0, expon.scaled = TRUE)
          + besselI(2*mu, 1, expon.scaled = TRUE))
E_max2 <- mu + sqrt(mu/pi)
#E_max
#E_max2
E_min <- mu - mu*(besselI(2*mu, 0, expon.scaled = TRUE)
          + besselI(2*mu, 1, expon.scaled = TRUE))
E_min2 <- mu - sqrt(mu/pi)
mean(Y_B)
#E_min
#E_min2

V_max <- mu - (mu*(besselI(2*mu, 0, expon.scaled = TRUE) + besselI(2*mu, 1, expon.scaled = TRUE)))^2 + mu*besselI(2*mu, 0, expon.scaled = TRUE)
V_max
V_min <- mu - (mu*(besselI(2*mu, 0, expon.scaled = TRUE) + besselI(2*mu, 1, expon.scaled = TRUE)))^2 - mu*besselI(2*mu, 0, expon.scaled = TRUE)
#V_min
var(Y_B)
#V_min
#var(Y_B)/V_min
#var(Z_B)/V_max
```


```{r}

```



```{r}
Ylast <- 200
alpha <- seq(.1,200,.1)
mu <- alpha*Ylast
besel <- 1/(besselI(2*mu, 0, expon.scaled = TRUE)
          + besselI(2*mu, 1, expon.scaled = TRUE))
plot((alpha+1),besel,ylim=c(-1,max(besel)))
abline(a=0,b=1)
```




```{r}
mu = .1
V_max <- mu - (mu*(besselI(2*mu, 0, expon.scaled = TRUE) + besselI(2*mu, 1, expon.scaled = TRUE)))^2 + mu*besselI(2*mu, 0, expon.scaled = TRUE)
V_max
```


```{r}
#simulation for D Poissons
D <- 67
mu <- 8
Y_B <- c()
Z_B <- c()
B <- 10000
for(i in 1:B){
  m_D <- rpois(D, mu)
  Y <- min(m_D)
  Z <- max(m_D) 
  Y_B <- c(Y_B, Y)
  Z_B <- c(Z_B, Z)
}
mean(Y_B)
#mean(Z_B)
#var(Y_B)
#var(Z_B)
#hist(Z_B)

beep <- function(mu){
  return(mu*(besselI(2*mu, 0, expon.scaled = TRUE)
          + besselI(2*mu, 1, expon.scaled = TRUE)))
}

E_max <- mu + beep(mu)*sum(1/1:(D-1))
#E_max2 <- mu + sqrt(mu/pi)
#E_max
#E_max2
E_min <- mu - mu*(besselI(2*mu, 0, expon.scaled = TRUE)
          + besselI(2*mu, 1, expon.scaled = TRUE))
E_min2 <- mu - sqrt(mu/pi)
E_min
E_min2
min_expectation2(mu,D)
# V_max <- mu - (mu*(besselI(2*mu, 0, expon.scaled = TRUE) + besselI(2*mu, 1, expon.scaled = TRUE)))^2 + mu*besselI(2*mu, 0, expon.scaled = TRUE)
# #V_max
# V_min <- mu - (mu*(besselI(2*mu, 0, expon.scaled = TRUE) + besselI(2*mu, 1, expon.scaled = TRUE)))^2 - mu*besselI(2*mu, 0, expon.scaled = TRUE)
#V_min
```

```{r}
mu <- 2
B <- 100
my_expec <- 0
for(x in 1:B){
  for(y in 1:B){
    for(z in 1:B){
      my_expec <- my_expec + mu^(x+y+z)/(factorial(x)*factorial(y)*factorial(z))*abs(x-.5*(y+z)-.5*abs(y-z))
    }
  }
}
```

```{r}
my_expec*exp(-3*mu)
mu*(besselI(2*mu, 0, expon.scaled = TRUE)
          + besselI(2*mu, 1, expon.scaled = TRUE))
```

```{r}
library(expint)
min_prob <- function(m, mu){
  g1 <- gamma(m+1)
  g2 <- gammainc(m+1, mu)
  term1 <- 2*exp(-mu)*mu^(m)*(g1-g2)/(g1^2)
  term2 <- mu^(2*m)*exp(-2*mu)/(g1^2)
  return(term1 + term2)
}
min_expectation <- function(mu){
  B <- 100
  result <- 0
  for(i in 1:B){
    result <- result + i*min_prob(i,mu)
  }
  return(result)
}
min_variance <- function(mu){
  B <- 100
  result <- 0
  for(i in 1:B){
    result <- result + (i)^2*min_prob(i,mu)
  }
  return(result - min_expectation(mu)^2)
}
```

```{r}
mu <- .001234
min_expectation(mu)
mu - mu*(besselI(2*mu, 0, expon.scaled = TRUE)
          + besselI(2*mu, 1, expon.scaled = TRUE))

min_variance(mu)
mu - (mu*(besselI(2*mu, 0, expon.scaled = TRUE) + besselI(2*mu, 1, expon.scaled = TRUE)))^2 - mu*besselI(2*mu, 0, expon.scaled = TRUE)
```

```{r}
library(expint)
max_prob <- function(m, mu){
  m <- m+1
  g1 <- gamma(m)
  g2 <- gammainc(m, mu)
  g3 <- gamma(m+1)
  term1 <- 2*exp(-mu)*mu^(m+1)*(g1-g2)/(g3^2)
  term2 <- mu^(2*m)*exp(-2*mu)/(g3^2)
  return(term1 + term2)
}
max_expectation <- function(mu){
  B <- 100
  result <- 0
  for(i in 1:B){
    result <- result + i*max_prob(i,mu)
  }
  return(result)
}
max_variance <- function(mu){
  B <- 150
  result <- 0
  for(i in 1:B){
    result <- result + (i)^2*min_prob(i,mu)
  }
  return(result - min_expectation(mu)^2)
}


round(sapply(0:9,max_prob,2),5)
max_expectation(mu)
mu + mu*(besselI(2*mu, 0, expon.scaled = TRUE)
          + besselI(2*mu, 1, expon.scaled = TRUE))
```



```{r}
table(Z_B)/B
```

```{r}
poisson_cdf <- function(k,mu){
  k <- floor(k)
  g1 <- gamma(k+1)
  g2 <- gammainc(k+1, mu)
  return(g2/g1)
}
min_cdf <- function(k,mu,d=2){
  return(1-(1-poisson_cdf(k,mu))^d)
}
```

```{r}
round(sapply(0:10,min_prob,2),5)
round(sapply(0:10,min_cdf,2),5)
min_expectation(2)
min_expectation2 <- function(mu,d=2){
  B <- 100
  result <- 0
  for(i in 0:100){
    result <- result + 1 - min_cdf(i,mu,d=d)
  }
  return(result)
}

```

```{r}
D <- 2
mu <- 2
Y_B <- c()
Z_B <- c()
B <- 100000
for(i in 1:B){
  m_D <- rpois(D, mu)
  Y <- min(m_D) 
  Z <- max(m_D)
  Y_B <- c(Y_B, Y)
  Z_B <- c(Z_B, Z)
}
M <- 5
m <- 1

```



```{r}
beep <- c(3,3,2)
beep <- beep[-which.max(beep)]
beep
```

```{r}
mu <- 2
m <- 0
D <- 40
Y_new <- c()
while(length(Y_new) <100000){
  m_D <- rpois(D, mu)
  Z <- min(m_D)
  if(Z == m){
    Y_new <- c(Y_new,m_D[-which.min(m_D)])
  }
}
sim <- round(table(Y_new)/length(Y_new),4)
```
```{r}
pmf_given_min <- function(k,m,mu){
  if(m > 0){
    sum <- 0
    for(j in 0:(m-1)){
      sum <- sum + exp(-mu)*(mu^j)/gamma(j+1)
    }
    return(exp(-mu)*(mu^k)/(gamma(k+1)*(1-sum)))
  }else{
    return((exp(-mu)*mu^k)/gamma(k+1))
  }
}
ztp <- function(k,mu){
  return(mu^k/(gamma(k+1)*(exp(mu)-1)))
}


max_obs <- max(as.numeric(names(sim)))
pred <- round(sapply(m:max_obs,ztp,mu),4)
df <- data.frame(sim, pred)
df
```

```{r}
B <- 10000
mu <- 2
beep <- c()
m <- 0
while(length(beep) < B){
  boop <- rpois(2,mu)
  minimum <- min(boop)
  if(minimum == 0){
    boop <- boop[-which.min(boop)]
    index <- sample.int(length(boop),size = 1)
    beep <- c(beep,boop[index])
  }
}
(sim <- table(beep)/B)
max_obs <- max(as.numeric(names(sim)))
round(sapply(m:max_obs,pmf_given_min,1,mu),4)
```
```{r}
sum(m:max_obs*sim)
mu + mu*(besselI(2*mu, 0, expon.scaled = TRUE)
          + besselI(2*mu, 1, expon.scaled = TRUE))
```

```{r}
mu <- 2
library(hypergeo)
first <- mu - .5*mu*(besselI(2*mu, 0, expon.scaled = TRUE)
          + besselI(2*mu, 1, expon.scaled = TRUE))
second <- -mu*(besselI(2*mu, 0)
          - besselI(2*mu, 1))*exp(-mu)
third <- -.5*mu*besselI(2*mu*sqrt(exp(1)), 0)*exp(-2*mu)
fourth <- -.5*mu*exp(1)*besselI(2*mu*sqrt(exp(1)), 0)*exp(-2*mu)
fifth <- -mu*genhypergeo(NULL, c(1,1), mu^3, tol=0, maxiter=2000, check_mod=TRUE, polynomial=FALSE, debug=FALSE, series=TRUE)
total <- first + second - third + fourth
total
```
```{r}
#simulation for 2 Poissons
D <- 3
mu <- 2
Y_B <- c()
Z_B <- c()
B <- 10000
for(i in 1:B){
  m_D <- rpois(D, mu)
  Y <- min(m_D) 
  Z <- max(m_D)
  Y_B <- c(Y_B, Y)
  Z_B <- c(Z_B, Z)
}
mean(Y_B)
```

```{r}
mu <- 4
X <- simcmp(n=10000, v = c(mu,1))
mean(X)
var(X)
```

```{r}
library(expint)
D <- 1000
mu <- 2
m <- 8
(gammainc(m+1, mu)/gamma(m+1))^D - (gammainc(m, mu)/gamma(m))^D
```

```{r}
#simulation for 2 Poissons
dlist <- list()
for(D in c(10, 100, 1000)){
  means_Z <- c()
  for(mu in 1:200){
    Y_B <- c()
    Z_B <- c()
    B <- 1000
    for(i in 1:B){
      m_D <- rpois(D, mu)
      Z <- max(m_D)
      Z_B <- c(Z_B, Z)
    }
    means_Z <- c(means_Z, mean(Z_B))
  }
  dlist[[as.character(D)]] <- means_Z
}
```

```{r}
#plot(1:150,dlist[['10']][1:150])
#points(1:150,mode_approx(1:150,10))
plot(1:150,dlist[['100']][1:150])
points(1:150,mode_approx(1:150,100))
# points(1:30,dlist[['1000']][1:30])
```


```{r}
pmax_pmf <- function(k, mu, D){
  beep <-(expint::gammainc(k+1, mu)/gamma(k+1))^D
  boop <-(expint::gammainc(k, mu)/gamma(k))^D
  return(c(beep,boop))
}
pmax_ex <- function(mu,D,B=100){
  result <- 0
  schedule <- data.frame(matrix(ncol=4,nrow=0, dimnames=list(NULL, c("weight", "first", "second","diff"))))
  for(i in 1:B){
    vec <- pmax_pmf(i,mu,D)
    first <- vec[1]
    second <- vec[2]
    result <- result + i*(first-second)
    if(i == 1){
      schedule[1,] <- c(i,first,second,first-second)
    }
    schedule <- rbind(schedule, c(i,first,second,first-second))
  }
  return(list(result,schedule))
}
mode_approx <- function(mu, D){
  x0 <- log(D)/(lambertWp(log(D)/(exp(1)*mu)))
  x1 <- x0 + (log(mu) - mu - log(2*pi)/2 - 3*log(x0)/2)/(log(x0)-log(mu))
  return(x1)
}

pmax_ex2 <- function(mu,D,B=100){
  result <- 0
  for(i in 1:B){
    print((expint::gammainc(i, mu)/gamma(i))^D)
    result <- result + (expint::gammainc(i, mu)/gamma(i))^D
  }
  return(-1*result)
}
beep <- pmax_ex(2,2)
beep[[1]]
beep[[2]]
```

```{r}
D <- 50
mu <- 50

mat_muD <- matrix(nrow = D, ncol = mu)
columns <- c("mean", "D", "mu")
reg_df <- data.frame(matrix(nrow = 0, ncol = length(columns))) 
colnames(reg_df) <- columns
for(i in 2:D){
  for(j in 1:mu){
    mat_muD[i,j] <- pmax_ex(j+10,i)
    if(nrow(reg_df) == 0){
      reg_df[1,] <- c(pmax_ex(j+10,i),i,j+10)
    }else{
      reg_df <- rbind(reg_df,c(pmax_ex(j+5,i),i,j+5))
    }
    
  }
}

```

```{r}
model <- lm(data = reg_df, mean ~ D + mu + D:mu)
summary(model)
plot(x=model$fitted.values,y=model$residuals, pch = '.')
```
```{r}
plot(y=reg_df$mean,x=reg_df$D)
```

```{r}
B <- 1000
D <- 5
max_B <- c()
for(i in 1:B){
  
  max_B <- c(max_B, max(rnbinom(D, size = 20, p = .5)))
}
mean(max_B )
var(max_B)
```

```{r}
pmax_pmf <- function(k, mu, D){
  beep <-(ppois(k,mu))^D
  boop <-(ppois(k-1,mu))^D
  return(beep-boop)
}
#the gamma count
library(rmutil)
k = 8
mu = 4
alpha = 4
dgammacount(k,mu,alpha)
pgamma(mu*alpha,k*alpha,1) - pgamma(mu*alpha,(k+1)*alpha,1) 
```
```{r}
k = 7
mu = 1
alpha = .25
D = 2
round(dgammacount(0:k,mu,alpha),3)
round(pmax_pmf(0:k,mu,D),3)
```
```{r}
k = 5
expint::gammainc(k+1, mu)/gamma(k+1)
ppois(5,mu)
```

```{r}
ex_count <- function(mu,D,B=100,count){
  result <- 0
  for(i in 1:B){
    result <- result + i*count(i,mu,D)
  }
  return(result)
}
var_count <- function(mu,D,B=100,count){
  result <- 0
  for(i in 1:B){
    result <- result + (i^2)*count(i,mu,D)
  }
  return(result - ex_count(mu,D,count=count)^2)
}
#ex_count(2,2,count=pmax_pmf)
#var_count(2,2,count=pmax_pmf)
ex_count(2,2,count=dgammacount)
var_count(2,2,count=dgammacount)
```

```{r}
hist(rpois(100000,20))
```

```{r}
B <- 10000
mu <-
x <- rpois(B,mu)
hist(x)
var(x)
mean(x)
```

