---
title: "Untitled"
output: html_document
date: "2024-08-07"
---

```{r}
library(COMPoissonReg)
```

```{r}
#simulate data from various CMP
B <- 1000
#nulist <- c(1.1,1.3,1.5,1.7,2,2.5,3.5,5,10)
nulist <- c(1,1.3)
clist <- c()
numDatasets <- 1
mat <- matrix(0, nrow=B+2,ncol=length(nulist)*numDatasets)
count <- 1
for(i in 1:length(nulist)){
  for(j in 1:numDatasets){
    set.seed(j)
    inflationpower <- (nulist[i] - 1)*10
    x <- rcmp(n=1000,lambda=100*1.586^inflationpower, nu=nulist[i])
    #print(mean(x))
    # print(nulist[i])
    print(var(x)/mean(x))
    mat[,count] <- c(nulist[i], j, x)
    count <- count + 1
  }
}

write.csv(mat, "CMPdata_choicefinal.csv")
#hist(x)
```

```{r}
#nulist <- c(1.1,1.3,1.5,1.7,2,2.5,3.5,5,10)
nulist <- c(1.3)
#compute PMF for those CMP
begin = 50
end = 150
count <- 1
mat <- matrix(0,nrow=length(nulist),ncol=length(begin:end))
for(nu in nulist){
  inflationpower <- (nu - 1)*10
  x <- dcmp(begin:end,lambda=100*1.586^inflationpower, nu=nu)
  mat[count,] <- x
  count <- count + 1
}
write.csv(mat, "CMPpmf_final.csv")
```



```{r}
# file <- "/Users/jimmylederman/Desktop/poisson_mf_julia/unimeans.csv"
# df <- read.csv(file)
# df
```





```{r}
# i <- 6
# nulist <- c(1.1,1.3,1.5,1.7,2,2.5,3.5,5,10)
# inflationpower <- (nulist[i] - 1)*10
# beep <- rep(0,1000)
# for(j in 1:1000){
#   x <- rcmp(n=1000,lambda=100*1.586^inflationpower, nu=nulist[i])
#   beep[j] <- var(x)/mean(x)
# }
# mean(beep)

```

```{r}
# B <- 1000000
# beeps <- rep(0, B)
# for(b in 1:B){
#   beeps[b] <- max(rnorm(3))
# }
```

```{r}
# mean(beeps)
# 3/(2*sqrt(pi))
# # 9/(4*pi)
# # (pi-1)/pi^2
# mean(beeps^2)
# 2*(pi-1)/pi
```

```{r}
nu <- 1.1
inflationpower <- (nu - 1)*10
x <- rcmp(n=10000,lambda=100*1.586^inflationpower, nu=nu)
var(x)/mean(x)
```

