---
title: "Untitled"
output: html_document
date: "2024-08-27"
---


```{r}
#simulate data from various gamma count distributions
B <- 1000
alphalist <- c(1.25,1.5,2,3,4,5,10)
numDatasets <- 5
mat <- matrix(0, nrow=B+2,ncol=length(alphalist)*numDatasets)
count <- 1
for(i in 1:length(alphalist)){
  for(j in 1:numDatasets){
    set.seed(j)
    Th <- 1
    alpha <- alphalist[i]
    beta <- 25*alpha
    x <- rep(0,B)
    for(b in 1:B){
      tau_n <- rgamma(n, alpha,beta)
      v_n <- cumsum(tau_n)
      x[b] <- sum(v_n <= Th)
    }
    mat[,count] <- c(alpha, j, x)
    count <- count + 1
  }
}

write.csv(mat, "/Users/jimmylederman/Desktop/synthetic/GammaCount/data/gcsamples.csv")
#hist(x)
```

```{r}
dgamma_count <- function(k,alpha,beta){
  return(ifelse(k == 0,1-pgamma(1,alpha*(k+1),beta),pgamma(1,alpha*k, beta) - pgamma(1,alpha*(k+1), beta)))
}
```


```{r}
alphalist <- c(1.25,1.5,2,3,4,5,10)
#compute PMF for those gamma count
begin = 0
end = 50
count <- 1
mat <- matrix(0,nrow=length(alphalist),ncol=length(begin:end))
for(alpha in alphalist){
  Th <- 1
  beta <- 25*alpha
  x <- dgamma_count(begin:end,alpha,beta*Th)
  mat[count,] <- x
  count <- count + 1
}
write.csv(mat, "/Users/jimmylederman/Desktop/synthetic/GammaCount/data/GCpmf.csv")
```





```{r}
lower_gamma_inc <- function(a,b){
  return(1-gammainc(a,b)/gamma(a))
}

betanew <- beta*Th
total = 0
xlist <- seq(0,1000,1)
problist <- rep(0,length(xlist))
total = 0 
for(i in 1:length(xlist)){
  n <- xlist[i]
  if(n == 0){
    #temp = 1-lower_gamma_inc(alpha*(n+1),betanew)
    temp = 1-pgamma(1,alpha*(n+1),betanew)
  }else{
    #temp = lower_gamma_inc(alpha*n, betanew) - lower_gamma_inc(alpha*(n+1), betanew)
    temp = pgamma(1,alpha*n, betanew) - pgamma(1,alpha*(n+1), betanew)
  }
  if(!is.na(temp)){
      problist[i] <- temp
    }else{
      problist[i] <- 0
    }
  total = total + temp
}

midpoints <- barplot(table(samp_B)/B,col=rgb(0, 0, 1, 0.5),ylim=c(0,max(problist)+.01))
points(midpoints,problist[as.numeric(names(table(samp_B))) + 1],pch=20)
```

```{r}
dgamma_count(0:50,1.2,25)
```





